### ISSUE TITLE
Is it possible to put calc() inside strip()?

### ISSUE THREAD

**Issue by RyoIkarashi** [whitneyit/postcss-strip-units#3]
When I put `calc()` function inside `strip()`, I get an error saying `Couldn't parse strip(calc(24px * 2)). Got NaN`.

I think this error occurs because `postcss-strip-units` is added before `postcss-calc`.
So I added postcss-calc twice before and after `postcss-strip-units`, but unfortunately it didn't work at all.

Any idea to achieve this or workaround?

The code is something like below.

variables.css

``` css
:root {
    --a-size: 24px;
    --b-size: calc(var(--a-size) * 2);
}
```

type.css

``` css
h1 {
    font-size: calc(strip(var(--b-size)) * 1 rem); /* => Couldn't parse strip(calc(24px * 2)) => NaN */
}
```

main.css

``` css
@import 'variables.css';
@import 'type.css';
```

PostCSS plugins order

```
require('postcss-devtools')(),
require('postcss-easy-import')({addDependencyTo: webpack,prefix: '_'}),
require('postcss-url')(),
require('postcss-mixins')(),
require('postcss-extend')(),
require('postcss-each')(),
require('postcss-for')(),
require('postcss-nth-list')(),
require('postcss-simple-vars')(),
require('postcss-custom-properties')(),
require('postcss-strip-units')(),
require('postcss-conditionals')(),
require('postcss-calc')({warnWhenCannotResolve: true}),
require('postcss-cssnext')({browsers: 'last 2 versions'}),
require('css-mqpacker')(),
require('postcss-utilities')(),
require('postcss-browser-reporter')(),
require('postcss-reporter')()
```

**Comment by whitneyit** [comment]
If you have a look at the example in the [`README.md`](https://github.com/whitneyit/postcss-strip-units/blob/master/README.md) this was achieve by first stripping both units then applying the `calc`.

```css
:root {
    --base-spacing-unit: 20px;
    --base-font-size: 14px;
    --rhythm: calc((strip(var(--base-spacing-unit)) / strip(var(--base-font-size))) * 1em);
}
```

If you could provide a failing pull request I can investigate this further.
